# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4

    working_directory: ~/repo

    steps:
      # Setup codecov env
      - run:
          name: Setup codecov env
          command: bash <(curl -s https://codecov.io/env)

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests!
      - run:
          name: Test
          command: yarn test

      - run:
          name: Generate code coverage
          command: "./node_modules/.bin/nyc report --reporter=text-lcov"
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

      # Report coverage
      - run:
          name: Generate code coverage
          command: bash <(curl -s https://codecov.io/bash)
